# Generated by Django 3.2.19 on 2023-07-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
