# Generated by Django 3.2.19 on 2023-07-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_homevideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vide_title', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
