# Generated by Django 3.2.19 on 2023-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_socialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
